name: Deploy Quartz Site to GitHub Pages

on:
  # Se ejecuta cada vez que subes cambios a la rama 'main'
  push:
    branches: ["main"]

# Permisos necesarios para que la acción pueda publicar en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Build Quartz
        uses: konstfish/quartz-build-action@v5
        with:
          # Le decimos a Quartz que nuestras notas están en la carpeta 'docs'
          source: docs 

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
